name: Code coverage

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run coverage
        run: tox -ecoverage
