name: Styles check

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run styles check
        run: tox -e linters
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Build docs
        run: tox -e docs
      - uses: actions/upload-artifact@v4
        with:
          name: html_docs
          path: docs/_build/html
