name: Release to PyPi and upload artifact

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release-package:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.x"
      - name: Install Deps
        run: pip install -U twine wheel
      - name: Build Artifacts
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/qiskit*
      - name: Publish to PyPi
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: twine upload dist/qiskit*
